### ISSUE TITLE
SQL (Android-SQLite, JDBC) support

### ISSUE THREAD

**Issue by Miha-x64** [Miha-x64/reactive-properties#32]
- [x] Prototype, SQLite, observability
- [x] SQL templates
- [x] Create trigger-based observability which will work for external INSERT/UPDATE/DELETE statements and for multi-node applications with a shared database
- [x] Support mutating SQL templates
- [x] deprecate DAOs and Records

**Comment by Badya** [comment]
While working with locks, especially combining with JDBC, you should always be aware of SQLException or other Throwable, so best-practice is:
```
try {
  lockObj.lock()
  // do smth what may cause Throwable
} catch(t: Throwable) {
  // optional catch, log, rollback, recover etc.
} finally {
  lockObj.unlock()
}
```

**Comment by Miha-x64** [comment]
Thanks.
Isn't this enough? https://github.com/Miha-x64/reactive-properties/commit/602558355d2936615ebec1622b92df7bb66ce43b#diff-573dde46d39b9c33095dc3e66c14a5f9R16
