### ISSUE TITLE
Migrate from jCenter to mavenCentral

### ISSUE THREAD

**Issue by mfperminov** [Miha-x64/reactive-properties#59]
Not available on bintray.
JCenter deprecation and end of service: https://developer.android.com/studio/build/jcenter-migration

Cannot sync project because of 403 forbidden error

**Comment by Miha-x64** [comment]
Yep, thanks, this is in progress. New version will be on Maven Central.

**Comment by Miha-x64** [comment]
Well, it's now available on `mavenCentral()` with groupId `su.lychee` and version `0.0.17`, but some pom.xml files are incorrect, so additional dependencies must be added by hand:
```
repositories {
    maven { url "https://jitpack.io" }
}
dependencies {
    implementation("com.github.Miha-x64.Kotlin-MPP_Collection_utils:Collection-utils-jvm:1.0-alpha05")
}
```
